version: '3.5'

services:
  kdd-wiki:
    environment:
      - "NEXT_WEBPACK_USEPOLLING=1"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-next
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules