FROM node:20-alpine AS base

# remind me to never use docker again <3
ARG AUTH_SECRET
ENV AUTH_SECRET=$AUTH_SECRET

ARG AUTH_GOOGLE_CLIENT_ID
ENV AUTH_GOOGLE_CLIENT_ID=$AUTH_GOOGLE_CLIENT_ID

ARG AUTH_GOOGLE_CLIENT_SECRET
ENV AUTH_GOOGLE_CLIENT_SECRET=$AUTH_GOOGLE_CLIENT_SECRET

ARG AUTH_KSU_CLIENT_ID
ENV AUTH_KSU_CLIENT_ID=$AUTH_KSU_CLIENT_ID

ARG AUTH_KSU_CLIENT_SECRET
ENV AUTH_KSU_CLIENT_SECRET=$AUTH_KSU_CLIENT_SECRET

ARG DB_NAME
ENV DB_NAME=$DB_NAME

ARG DB_HOST
ENV DB_HOST=$DB_HOST

ARG DB_USERNAME
ENV DB_USERNAME=$DB_USERNAME

ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD

# DEVELOPMENT
FROM base AS dev

ENV CHOKIDAR_USEPOLLING=true
ENV NEXT_WEBPACK_USEPOLLING=true

WORKDIR /app
COPY package*.json ./
RUN npm install
# COPY --from=deps /app/node_modules ./node_modules

COPY . .
EXPOSE 3000
CMD npm run dev

# PRODUCTION
FROM base AS prod

WORKDIR /app

ENV CI=true

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
RUN npm run ci-test


EXPOSE 3000
CMD node .next/standalone/server.js