services:
  kdd-wiki-dev:
    container_name: kdd-wiki-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    command: npm run dev
    environment:
      - NODE_ENV=development
      - "NEXT_WEBPACK_USEPOLLING=1"
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    env_file:
      - .env.developer

  kdd-wiki-prod:
    container_name: kdd-wiki-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: always
    command: npm run start
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    env_file:
      - .env.production