# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kdd-wiki-website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Restart Docker
      run: sudo systemctl restart docker

    - name: Log in to registry
      uses: docker/login-action@v3
      with: 
        registry: ${{ secrets.CONTAINERREGISTRY }}
        username: ${{ secrets.CONTAINERREGISTRYUSERNAME }}
        password: ${{ secrets.CONTAINERREGISTRYPASSWORD }}

    - name: Create .env.local with secrets
      run: |
        echo $'AUTH_SECRET="${{ secrets.AUTH_SECRET }}"\n' >> .env.local
        echo $'AUTH_GOOGLE_CLIENT_ID="${{ secrets.AUTH_GOOGLE_CLIENT_ID }}"\n' >> .env.local
        echo $'AUTH_GOOGLE_CLIENT_SECRET="${{ secrets.AUTH_GOOGLE_CLIENT_SECRET }}"\n' >> .env.local
        echo $'AUTH_KSU_CLIENT_ID="${{ secrets.AUTH_KSU_CLIENT_ID }}"\n' >> .env.local
        echo $'AUTH_KSU_CLIENT_SECRET="${{ secrets.AUTH_KSU_CLIENT_SECRET }}"\n' >> .env.local
        echo $'DB_NAME="${{ secrets.DB_NAME }}"\n' >> .env.local
        echo $'DB_HOST="${{ secrets.DB_HOST }}"\n' >> .env.local
        echo $'DB_USERNAME="${{ secrets.DB_USERNAME }}"\n' >> .env.local
        echo $'DB_PASSWORD="${{ secrets.DB_PASSWORD }}"\n' >> .env.local
        echo $'LOADED=true\n' >> .env.local
        echo $'GITHUB_ACTIONS=true\n' >> .env.local
        echo $'BLOB_STORAGE_ACCOUNT_NAME="${{ secrets.BLOB_STORAGE_ACCOUNT_NAME }}"\n' >> .env.local
        echo $'BLOB_STORAGE_ACCOUNT_KEY="${{ secrets.BLOB_STORAGE_ACCOUNT_KEY }}"\n' >> .env.local
        echo $'BLOB_STORAGE_CONTAINER_NAME="${{ secrets.BLOB_STORAGE_CONTAINER_NAME }}"\n' >> .env.local

    # give permissions to the .env.local file
    - name: Give permissions to .env.local
      run: chmod 644 .env.local

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.CONTAINERREGISTRY }}/${{ secrets.CONTAINERREGISTRYUSERNAME }}/kdd-wiki:latest
        file: ./Dockerfile
        builder: mybuilder
        network: host

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: Azure/webapps-deploy@v3.0.1
        with:
          app-name: 'kdd-wiki-website'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_0a6678781b5e4a36850720ab95d56538 }}
          images: '${{ secrets.ContainerRegistry }}/${{ secrets.ContainerRegistryUsername }}/kdd-wiki:latest'
          slot-name: 'production'
          restart: true
